"""add_cod_fields_to_orders

Revision ID: 32b499d8f808
Revises: 0da7013e3d59
Create Date: 2026-01-07 22:56:09.722841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32b499d8f808'
down_revision: Union[str, None] = '0da7013e3d59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
