"""Add discount_percentage to products

Revision ID: e70b417f6c34
Revises: 48dbed2ea0c8
Create Date: 2026-01-08 11:56:45.522729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70b417f6c34'
down_revision: Union[str, None] = '48dbed2ea0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('discount_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'discount_percentage')
    # ### end Alembic commands ###
